version: "3"
services: 
   mongo:
      container_name: mongo-container
      image: mongo:3
      restart: always
      volumes:
        - ../data:/data/db
      ports:
        - "27017:27017"
   api:
      container_name: api-container
      image: node:15
      working_dir: /usr/app
      command: bash -c "npm i --only=prod && npm run debug"
      environment: 
        - MONGO_URL=mongodb://mongo:27017/clean-node-api
      restart: always
      volumes: 
        - ./dist/:/usr/app/dist/
        - ./package.json:/usr/app/package.json
      ports:
        - "3000:3000"
        - "9222:9222"
      links:
        - mongo

