version: "3"
services: 
   mongo:
      container_name: mongo-container
      image: mongo:3
      restart: always
      volumes:
        - ../data:/data/db
      ports:
        - "27017:27017"
   api:
      container_name: api-container
      build: .
      image: clean-node-api
      restart: always
      command: npm start
      volumes: 
        - ./dist:/usr/app/dist
      ports:
        - "3000:3000"
      links:
        - mongo
      env_file: .env
